// Fähigkeiten-Definitionen für den rundenbasierten Arena-Kampf

import { UnitElement } from '../units/UnitConfig';

export type AbilityTarget = 'single_enemy' | 'all_enemies' | 'single_ally' | 'all_allies' | 'self';

export interface ArenaAbilityDef {
  id: string;
  name: string;          // Deutscher Name
  description: string;   // Deutsche Beschreibung
  mpCost: number;
  cooldown: number;      // Runden zwischen Nutzungen
  targetType: AbilityTarget;
  element: UnitElement;
  // Schadens-/Heilungswerte (0 wenn nicht zutreffend)
  baseDamage: number;
  baseHealing: number;
  // Spezialeffekte
  effect?: AbilityEffect;
  // Spezialflaggen
  selfDestruct?: boolean;   // Einheit stirbt nach Einsatz
  revive?: boolean;         // Kann tote Einheiten wiederbeleben
  drainHealing?: boolean;   // Heilt den Anwender um den verursachten Schaden
}

export interface AbilityEffect {
  type: 'burn' | 'freeze' | 'slow' | 'poison' | 'stun' | 'shield' | 'taunt' | 'regen' | 'buff_atk' | 'buff_def' | 'debuff_atk' | 'debuff_def';
  duration: number;   // Runden
  value: number;       // Effektstärke (Schaden/Runde für DoTs, Multiplikator für Buffs)
}

export interface ActiveAbility {
  def: ArenaAbilityDef;
  currentCooldown: number;
}

// ─── Fähigkeiten aller 20 Einheiten ─────────────────────────────────────────

export const ARENA_ABILITIES: Record<string, ArenaAbilityDef[]> = {

  // ─── Bogenschütze (archer) ─────────────────────────────────────────────────
  archer: [
    {
      id: 'archer_1',
      name: 'Gezielter Schuss',
      description: 'Ein präziser Pfeil auf ein einzelnes Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 15,
      baseHealing: 0,
    },
    {
      id: 'archer_2',
      name: 'Pfeilhagel',
      description: 'Ein Regen aus Pfeilen trifft alle Gegner.',
      mpCost: 3,
      cooldown: 2,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 8,
      baseHealing: 0,
    },
    {
      id: 'archer_3',
      name: 'Schwachstelle',
      description: 'Zielt auf eine verwundbare Stelle und ignoriert Rüstung.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 25,
      baseHealing: 0,
    },
    {
      id: 'archer_4',
      name: 'Ausweichen',
      description: 'Erhöht die eigene Verteidigung für 2 Runden.',
      mpCost: 2,
      cooldown: 3,
      targetType: 'self',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_def', duration: 2, value: 2.0 },
    },
  ],

  // ─── Kanonier (cannoneer) ──────────────────────────────────────────────────
  cannoneer: [
    {
      id: 'cannoneer_1',
      name: 'Kanonenschuss',
      description: 'Ein wuchtiger Kanonenschuss auf ein einzelnes Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 40,
      baseHealing: 0,
    },
    {
      id: 'cannoneer_2',
      name: 'Explosivgeschoss',
      description: 'Explodierende Munition trifft alle Gegner.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 25,
      baseHealing: 0,
    },
    {
      id: 'cannoneer_3',
      name: 'Panzerbrecher',
      description: 'Durchschlägt die Rüstung und senkt die Verteidigung des Ziels.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 60,
      baseHealing: 0,
      effect: { type: 'debuff_def', duration: 2, value: 0.5 },
    },
    {
      id: 'cannoneer_4',
      name: 'Nachladen',
      description: 'Konzentriert sich und erhöht den eigenen Angriff für 2 Runden.',
      mpCost: 2,
      cooldown: 3,
      targetType: 'self',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_atk', duration: 2, value: 1.5 },
    },
  ],

  // ─── Frostmagier (frost_mage) ──────────────────────────────────────────────
  frost_mage: [
    {
      id: 'frost_mage_1',
      name: 'Eissplitter',
      description: 'Schleudert einen Eissplitter, der das Ziel verlangsamt.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'ice',
      baseDamage: 8,
      baseHealing: 0,
      effect: { type: 'slow', duration: 2, value: 0.5 },
    },
    {
      id: 'frost_mage_2',
      name: 'Frostnova',
      description: 'Eine Frostexplosion friert alle Gegner für 1 Runde ein.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'ice',
      baseDamage: 12,
      baseHealing: 0,
      effect: { type: 'freeze', duration: 1, value: 0 },
    },
    {
      id: 'frost_mage_3',
      name: 'Eisrüstung',
      description: 'Umhüllt einen Verbündeten mit Eis und erhöht die Verteidigung.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'single_ally',
      element: 'ice',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_def', duration: 3, value: 1.8 },
    },
    {
      id: 'frost_mage_4',
      name: 'Blizzard',
      description: 'Ein eisiger Sturm verlangsamt alle Gegner erheblich.',
      mpCost: 5,
      cooldown: 4,
      targetType: 'all_enemies',
      element: 'ice',
      baseDamage: 6,
      baseHealing: 0,
      effect: { type: 'slow', duration: 3, value: 0.3 },
    },
  ],

  // ─── Feuermagier (fire_mage) ───────────────────────────────────────────────
  fire_mage: [
    {
      id: 'fire_mage_1',
      name: 'Feuerball',
      description: 'Schleudert einen Feuerball, der das Ziel verbrennt.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'fire',
      baseDamage: 12,
      baseHealing: 0,
      effect: { type: 'burn', duration: 2, value: 5 },
    },
    {
      id: 'fire_mage_2',
      name: 'Flammenwand',
      description: 'Eine Feuerwand verbrennt alle Gegner.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'all_enemies',
      element: 'fire',
      baseDamage: 8,
      baseHealing: 0,
      effect: { type: 'burn', duration: 2, value: 4 },
    },
    {
      id: 'fire_mage_3',
      name: 'Feuerexplosion',
      description: 'Eine gewaltige Feuerexplosion mit massivem Schaden.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'fire',
      baseDamage: 35,
      baseHealing: 0,
    },
    {
      id: 'fire_mage_4',
      name: 'Inferno',
      description: 'Entfesselt ein Inferno, das alle Gegner schwer verbrennt.',
      mpCost: 7,
      cooldown: 4,
      targetType: 'all_enemies',
      element: 'fire',
      baseDamage: 20,
      baseHealing: 0,
      effect: { type: 'burn', duration: 3, value: 6 },
    },
  ],

  // ─── Scharfschütze (sniper) ────────────────────────────────────────────────
  sniper: [
    {
      id: 'sniper_1',
      name: 'Präzisionsschuss',
      description: 'Ein präziser Schuss mit höchster Genauigkeit.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 120,
      baseHealing: 0,
    },
    {
      id: 'sniper_2',
      name: 'Kopfschuss',
      description: 'Ein tödlicher Schuss auf den Kopf des Ziels.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 200,
      baseHealing: 0,
    },
    {
      id: 'sniper_3',
      name: 'Rauchbombe',
      description: 'Wirft eine Rauchbombe, die den Angriff aller Gegner senkt.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'debuff_atk', duration: 2, value: 0.6 },
    },
    {
      id: 'sniper_4',
      name: 'Markierung',
      description: 'Markiert ein Ziel und senkt dessen Verteidigung erheblich.',
      mpCost: 2,
      cooldown: 2,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'debuff_def', duration: 3, value: 0.4 },
    },
  ],

  // ─── Blitzmagier (lightning_mage) ──────────────────────────────────────────
  lightning_mage: [
    {
      id: 'lightning_mage_1',
      name: 'Blitzschlag',
      description: 'Ein schneller Blitz trifft ein einzelnes Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'lightning',
      baseDamage: 25,
      baseHealing: 0,
    },
    {
      id: 'lightning_mage_2',
      name: 'Kettenblitz',
      description: 'Ein Blitz springt zwischen allen Gegnern.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'all_enemies',
      element: 'lightning',
      baseDamage: 15,
      baseHealing: 0,
    },
    {
      id: 'lightning_mage_3',
      name: 'Energieschild',
      description: 'Erzeugt ein Energieschild, das Schaden absorbiert.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'self',
      element: 'lightning',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'shield', duration: 2, value: 30 },
    },
    {
      id: 'lightning_mage_4',
      name: 'Donnerschlag',
      description: 'Ein gewaltiger Donner betäubt das Ziel.',
      mpCost: 6,
      cooldown: 4,
      targetType: 'single_enemy',
      element: 'lightning',
      baseDamage: 50,
      baseHealing: 0,
      effect: { type: 'stun', duration: 1, value: 0 },
    },
  ],

  // ─── Mörserschütze (mortar) ────────────────────────────────────────────────
  mortar: [
    {
      id: 'mortar_1',
      name: 'Mörsergranate',
      description: 'Feuert eine Mörsergranate auf ein einzelnes Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 60,
      baseHealing: 0,
    },
    {
      id: 'mortar_2',
      name: 'Flächenbombardement',
      description: 'Bombardiert das gesamte Schlachtfeld.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 35,
      baseHealing: 0,
    },
    {
      id: 'mortar_3',
      name: 'Brandgranate',
      description: 'Eine Brandgranate setzt alle Gegner in Flammen.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 15,
      baseHealing: 0,
      effect: { type: 'burn', duration: 3, value: 8 },
    },
    {
      id: 'mortar_4',
      name: 'Erschütterung',
      description: 'Eine erschütternde Explosion betäubt alle Gegner.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 10,
      baseHealing: 0,
      effect: { type: 'stun', duration: 1, value: 0 },
    },
  ],

  // ─── Giftmischer (alchemist) ──────────────────────────────────────────────
  alchemist: [
    {
      id: 'alchemist_1',
      name: 'Gifttrank',
      description: 'Wirft einen Gifttrank, der das Ziel vergiftet.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'poison',
      baseDamage: 5,
      baseHealing: 0,
      effect: { type: 'poison', duration: 3, value: 8 },
    },
    {
      id: 'alchemist_2',
      name: 'Giftwolke',
      description: 'Eine giftige Wolke vergiftet alle Gegner.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'poison',
      baseDamage: 3,
      baseHealing: 0,
      effect: { type: 'poison', duration: 3, value: 5 },
    },
    {
      id: 'alchemist_3',
      name: 'Säureflasche',
      description: 'Säure zerfrißt die Rüstung des Ziels.',
      mpCost: 3,
      cooldown: 2,
      targetType: 'single_enemy',
      element: 'poison',
      baseDamage: 10,
      baseHealing: 0,
      effect: { type: 'debuff_def', duration: 3, value: 0.5 },
    },
    {
      id: 'alchemist_4',
      name: 'Antidot',
      description: 'Braut ein Heilmittel für einen Verbündeten.',
      mpCost: 2,
      cooldown: 2,
      targetType: 'single_ally',
      element: 'poison',
      baseDamage: 0,
      baseHealing: 30,
    },
  ],

  // ─── Laseringenieur (laser_tech) ──────────────────────────────────────────
  laser_tech: [
    {
      id: 'laser_tech_1',
      name: 'Laserstrahl',
      description: 'Feuert einen gebündelten Laserstrahl.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'arcane',
      baseDamage: 15,
      baseHealing: 0,
    },
    {
      id: 'laser_tech_2',
      name: 'Hyperstrahl',
      description: 'Ein übermächtiger Laserstrahl mit verheerender Wirkung.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'arcane',
      baseDamage: 50,
      baseHealing: 0,
    },
    {
      id: 'laser_tech_3',
      name: 'Energiefeld',
      description: 'Erzeugt ein schützendes Energiefeld für alle Verbündeten.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_allies',
      element: 'arcane',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'shield', duration: 2, value: 15 },
    },
    {
      id: 'laser_tech_4',
      name: 'Überladen',
      description: 'Überlädt die eigenen Systeme für massiven Angriffsboost.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'self',
      element: 'arcane',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_atk', duration: 3, value: 2.0 },
    },
  ],

  // ─── Windstoßer (wind_caller) ─────────────────────────────────────────────
  wind_caller: [
    {
      id: 'wind_caller_1',
      name: 'Windstoß',
      description: 'Ein kräftiger Windstoß trifft das Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'nature',
      baseDamage: 8,
      baseHealing: 0,
    },
    {
      id: 'wind_caller_2',
      name: 'Wirbelsturm',
      description: 'Ein Wirbelsturm erfasst alle Gegner.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'all_enemies',
      element: 'nature',
      baseDamage: 12,
      baseHealing: 0,
    },
    {
      id: 'wind_caller_3',
      name: 'Rückenwind',
      description: 'Stärkt den Angriff aller Verbündeten mit günstigem Wind.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'all_allies',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_atk', duration: 2, value: 1.3 },
    },
    {
      id: 'wind_caller_4',
      name: 'Windschild',
      description: 'Ein Windschild erhöht die Verteidigung eines Verbündeten.',
      mpCost: 2,
      cooldown: 2,
      targetType: 'single_ally',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_def', duration: 2, value: 1.5 },
    },
  ],

  // ─── Erzmagier (archmage) ─────────────────────────────────────────────────
  archmage: [
    {
      id: 'archmage_1',
      name: 'Arkangeschoss',
      description: 'Verschießt ein arkan geladenes Geschoss.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'arcane',
      baseDamage: 30,
      baseHealing: 0,
    },
    {
      id: 'archmage_2',
      name: 'Arkanexplosion',
      description: 'Eine arkane Explosion trifft alle Gegner.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'arcane',
      baseDamage: 20,
      baseHealing: 0,
    },
    {
      id: 'archmage_3',
      name: 'Manaschild',
      description: 'Ein mächtiger Manaschild absorbiert großen Schaden.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'self',
      element: 'arcane',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'shield', duration: 3, value: 40 },
    },
    {
      id: 'archmage_4',
      name: 'Arkansturm',
      description: 'Ein verheerender Arkansturm schwächt und trifft alle Gegner.',
      mpCost: 7,
      cooldown: 4,
      targetType: 'all_enemies',
      element: 'arcane',
      baseDamage: 30,
      baseHealing: 0,
      effect: { type: 'debuff_def', duration: 2, value: 0.6 },
    },
  ],

  // ─── Flammenwerfer (pyro) ─────────────────────────────────────────────────
  pyro: [
    {
      id: 'pyro_1',
      name: 'Flammenstrahl',
      description: 'Ein heißer Flammenstrahl verbrennt das Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'fire',
      baseDamage: 10,
      baseHealing: 0,
      effect: { type: 'burn', duration: 2, value: 4 },
    },
    {
      id: 'pyro_2',
      name: 'Feuersturm',
      description: 'Ein Feuersturm verbrennt alle Gegner.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'all_enemies',
      element: 'fire',
      baseDamage: 8,
      baseHealing: 0,
      effect: { type: 'burn', duration: 2, value: 6 },
    },
    {
      id: 'pyro_3',
      name: 'Napalm',
      description: 'Napalm haftet an Gegnern und brennt lang und intensiv.',
      mpCost: 5,
      cooldown: 4,
      targetType: 'all_enemies',
      element: 'fire',
      baseDamage: 5,
      baseHealing: 0,
      effect: { type: 'burn', duration: 4, value: 8 },
    },
    {
      id: 'pyro_4',
      name: 'Hitzeresistenz',
      description: 'Stählt sich gegen Hitze und erhöht die eigene Verteidigung.',
      mpCost: 2,
      cooldown: 3,
      targetType: 'self',
      element: 'fire',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_def', duration: 3, value: 1.6 },
    },
  ],

  // ─── Schildträger (guardian) ───────────────────────────────────────────────
  guardian: [
    {
      id: 'guardian_1',
      name: 'Schildhieb',
      description: 'Schlägt mit dem Schild zu und zwingt Gegner zum Angriff.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'ice',
      baseDamage: 5,
      baseHealing: 0,
      effect: { type: 'taunt', duration: 2, value: 0 },
    },
    {
      id: 'guardian_2',
      name: 'Schutzschild',
      description: 'Erzeugt einen mächtigen Schutzschild für einen Verbündeten.',
      mpCost: 3,
      cooldown: 2,
      targetType: 'single_ally',
      element: 'ice',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'shield', duration: 2, value: 40 },
    },
    {
      id: 'guardian_3',
      name: 'Provokation',
      description: 'Provoziert Gegner und stärkt die eigene Verteidigung massiv.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'self',
      element: 'ice',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'taunt', duration: 3, value: 2.0 },
    },
    {
      id: 'guardian_4',
      name: 'Festung',
      description: 'Verwandelt sich in eine uneinnehmbare Festung.',
      mpCost: 5,
      cooldown: 4,
      targetType: 'self',
      element: 'ice',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'shield', duration: 3, value: 60 },
    },
  ],

  // ─── Nekromant (necromancer) ───────────────────────────────────────────────
  necromancer: [
    {
      id: 'necromancer_1',
      name: 'Schattenblitz',
      description: 'Ein dunkler Blitz trifft das Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'dark',
      baseDamage: 20,
      baseHealing: 0,
    },
    {
      id: 'necromancer_2',
      name: 'Seelenentzug',
      description: 'Entzieht dem Ziel die Lebenskraft und heilt sich selbst.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'single_enemy',
      element: 'dark',
      baseDamage: 25,
      baseHealing: 25,
      drainHealing: true,
    },
    {
      id: 'necromancer_3',
      name: 'Fluch',
      description: 'Verflucht ein Ziel und schwächt Angriff und Verteidigung.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'dark',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'debuff_atk', duration: 3, value: 0.5 },
    },
    {
      id: 'necromancer_4',
      name: 'Dunkle Ernte',
      description: 'Dunkle Energie schadet Gegnern und heilt alle Verbündeten.',
      mpCost: 6,
      cooldown: 4,
      targetType: 'all_enemies',
      element: 'dark',
      baseDamage: 15,
      baseHealing: 10,
    },
  ],

  // ─── Erderschütterer (earth_shaker) ───────────────────────────────────────
  earth_shaker: [
    {
      id: 'earth_shaker_1',
      name: 'Erdschlag',
      description: 'Ein gewaltiger Schlag mit der Kraft der Erde.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'nature',
      baseDamage: 35,
      baseHealing: 0,
    },
    {
      id: 'earth_shaker_2',
      name: 'Erdbeben',
      description: 'Ein Erdbeben erschüttert alle Gegner und betäubt sie.',
      mpCost: 5,
      cooldown: 4,
      targetType: 'all_enemies',
      element: 'nature',
      baseDamage: 25,
      baseHealing: 0,
      effect: { type: 'stun', duration: 1, value: 0 },
    },
    {
      id: 'earth_shaker_3',
      name: 'Steinwand',
      description: 'Errichtet eine Steinwand zur eigenen Verteidigung.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'self',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_def', duration: 3, value: 2.0 },
    },
    {
      id: 'earth_shaker_4',
      name: 'Erdrutsch',
      description: 'Ein Erdrutsch trifft und verlangsamt alle Gegner.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'nature',
      baseDamage: 20,
      baseHealing: 0,
      effect: { type: 'slow', duration: 2, value: 0.5 },
    },
  ],

  // ─── Heiler (healer) ──────────────────────────────────────────────────────
  healer: [
    {
      id: 'healer_1',
      name: 'Heilzauber',
      description: 'Heilt einen Verbündeten mit heiliger Magie.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_ally',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 25,
    },
    {
      id: 'healer_2',
      name: 'Gruppenheilung',
      description: 'Heilt alle Verbündeten gleichzeitig.',
      mpCost: 4,
      cooldown: 2,
      targetType: 'all_allies',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 15,
    },
    {
      id: 'healer_3',
      name: 'Wiederbelebung',
      description: 'Belebt einen gefallenen Verbündeten wieder.',
      mpCost: 6,
      cooldown: 5,
      targetType: 'single_ally',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 50,
      revive: true,
    },
    {
      id: 'healer_4',
      name: 'Segen',
      description: 'Segnet einen Verbündeten mit Heilung und Regeneration.',
      mpCost: 3,
      cooldown: 2,
      targetType: 'single_ally',
      element: 'nature',
      baseDamage: 0,
      baseHealing: 10,
      effect: { type: 'regen', duration: 3, value: 8 },
    },
  ],

  // ─── Sprengmeister (bomber) ────────────────────────────────────────────────
  bomber: [
    {
      id: 'bomber_1',
      name: 'Bombe werfen',
      description: 'Wirft eine Bombe auf ein einzelnes Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 50,
      baseHealing: 0,
    },
    {
      id: 'bomber_2',
      name: 'Großexplosion',
      description: 'Eine gewaltige Explosion trifft alle Gegner.',
      mpCost: 5,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 30,
      baseHealing: 0,
    },
    {
      id: 'bomber_3',
      name: 'Minenfalle',
      description: 'Platziert eine Mine, die das Ziel betäubt.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 40,
      baseHealing: 0,
      effect: { type: 'stun', duration: 1, value: 0 },
    },
    {
      id: 'bomber_4',
      name: 'Selbstzerstörung',
      description: 'Opfert sich selbst für verheerenden Flächenschaden.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 100,
      baseHealing: 0,
      selfDestruct: true,
    },
  ],

  // ─── Fallensteller (trapper) ──────────────────────────────────────────────
  trapper: [
    {
      id: 'trapper_1',
      name: 'Stachelattacke',
      description: 'Greift mit vergifteten Stacheln an und verlangsamt das Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 10,
      baseHealing: 0,
      effect: { type: 'slow', duration: 2, value: 0.5 },
    },
    {
      id: 'trapper_2',
      name: 'Fangnetz',
      description: 'Wirft ein Netz, das das Ziel für 2 Runden betäubt.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'stun', duration: 2, value: 0 },
    },
    {
      id: 'trapper_3',
      name: 'Giftnadeln',
      description: 'Verschießt Giftnadeln auf alle Gegner.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'physical',
      baseDamage: 5,
      baseHealing: 0,
      effect: { type: 'poison', duration: 3, value: 4 },
    },
    {
      id: 'trapper_4',
      name: 'Hinterhalt',
      description: 'Bereitet einen Hinterhalt vor und verdoppelt den eigenen Angriff.',
      mpCost: 2,
      cooldown: 3,
      targetType: 'self',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_atk', duration: 2, value: 2.0 },
    },
  ],

  // ─── Frostbomber (frost_bomber) ────────────────────────────────────────────
  frost_bomber: [
    {
      id: 'frost_bomber_1',
      name: 'Frostbombe',
      description: 'Wirft eine eiskalte Bombe auf das Ziel.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'ice',
      baseDamage: 20,
      baseHealing: 0,
    },
    {
      id: 'frost_bomber_2',
      name: 'Frostnebel',
      description: 'Ein eisiger Nebel verlangsamt alle Gegner erheblich.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_enemies',
      element: 'ice',
      baseDamage: 10,
      baseHealing: 0,
      effect: { type: 'slow', duration: 3, value: 0.4 },
    },
    {
      id: 'frost_bomber_3',
      name: 'Kälteschock',
      description: 'Ein Kälteschock friert das Ziel komplett ein.',
      mpCost: 5,
      cooldown: 4,
      targetType: 'single_enemy',
      element: 'ice',
      baseDamage: 35,
      baseHealing: 0,
      effect: { type: 'freeze', duration: 2, value: 0 },
    },
    {
      id: 'frost_bomber_4',
      name: 'Eisbarriere',
      description: 'Erzeugt eine schützende Eisbarriere für einen Verbündeten.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'single_ally',
      element: 'ice',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'shield', duration: 2, value: 25 },
    },
  ],

  // ─── Goldgräber (prospector) ──────────────────────────────────────────────
  prospector: [
    {
      id: 'prospector_1',
      name: 'Schaufelschlag',
      description: 'Schlägt mit der Schaufel auf das Ziel ein.',
      mpCost: 0,
      cooldown: 0,
      targetType: 'single_enemy',
      element: 'physical',
      baseDamage: 5,
      baseHealing: 0,
    },
    {
      id: 'prospector_2',
      name: 'Goldstaub',
      description: 'Magischer Goldstaub stärkt den Angriff aller Verbündeten.',
      mpCost: 3,
      cooldown: 3,
      targetType: 'all_allies',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'buff_atk', duration: 2, value: 1.2 },
    },
    {
      id: 'prospector_3',
      name: 'Glücksbonus',
      description: 'Glücklich gefundene Schätze regenerieren Lebenskraft.',
      mpCost: 2,
      cooldown: 2,
      targetType: 'self',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 0,
      effect: { type: 'regen', duration: 3, value: 5 },
    },
    {
      id: 'prospector_4',
      name: 'Schatzfund',
      description: 'Ein Schatzfund heilt alle Verbündeten.',
      mpCost: 4,
      cooldown: 3,
      targetType: 'all_allies',
      element: 'physical',
      baseDamage: 0,
      baseHealing: 20,
    },
  ],
};

// ─── Hilfsfunktionen ────────────────────────────────────────────────────────

/**
 * Gibt die Fähigkeiten einer Einheit zurück.
 * Falls keine definiert sind, wird ein leeres Array zurückgegeben.
 */
export function getAbilitiesForUnit(unitId: string): ArenaAbilityDef[] {
  return ARENA_ABILITIES[unitId] || [];
}

/**
 * Erstellt aktive Fähigkeiten (mit Cooldown-Tracking) für eine Einheit.
 */
export function createActiveAbilities(unitId: string): ActiveAbility[] {
  const abilities = getAbilitiesForUnit(unitId);
  return abilities.map(def => ({
    def,
    currentCooldown: 0,
  }));
}
