// Central balance configuration - all game numbers in one place

export const BALANCE = {
  // Player
  startGold: 100,
  baseHP: 1000,

  // Economy
  goldPerKill: {
    normal: 5,
    fast: 6,
    tank: 12,
    boss: 30,
    flyer: 8,
    healer: 10,
    splitter: 15,
    mini_splitter: 3,
  },
  goldPerWave: 25,

  // Waves
  totalWaves: 10,
  timeBetweenSpawns: 0.8, // seconds between each zombie
  waveBreakTime: 5, // seconds between waves (if auto)

  // Zombie stats: [hp, speed, damage, scale]
  zombies: {
    normal: { hp: 100, speed: 2.0, damage: 10, scale: 1.0, color: 0x2d8a4e },
    fast:   { hp: 60,  speed: 3.5, damage: 8,  scale: 0.8, color: 0x8a2d2d },
    tank:   { hp: 400, speed: 1.2, damage: 25, scale: 1.4, color: 0x4a2d8a },
    boss:   { hp: 2000, speed: 0.8, damage: 100, scale: 2.0, color: 0x8a0000 },
    flyer:  { hp: 80,  speed: 2.5, damage: 12,  scale: 0.7, color: 0x44aaff },
    healer: { hp: 120, speed: 1.5, damage: 8,   scale: 0.9, color: 0x44ff88 },
    splitter: { hp: 150, speed: 1.8, damage: 15, scale: 1.1, color: 0xffaa44 },
    mini_splitter: { hp: 50, speed: 2.5, damage: 5, scale: 0.5, color: 0xffcc66 },
  },

  // Wave definitions: [zombieType, count][]
  waves: [
    [{ type: 'normal', count: 8 }],
    [{ type: 'normal', count: 12 }],
    [{ type: 'normal', count: 10 }, { type: 'fast', count: 5 }],
    [{ type: 'fast', count: 15 }],
    [{ type: 'normal', count: 10 }, { type: 'tank', count: 3 }],
    [{ type: 'fast', count: 12 }, { type: 'tank', count: 5 }],
    [{ type: 'normal', count: 15 }, { type: 'fast', count: 10 }, { type: 'tank', count: 3 }],
    [{ type: 'tank', count: 10 }, { type: 'fast', count: 8 }],
    [{ type: 'normal', count: 20 }, { type: 'fast', count: 15 }, { type: 'tank', count: 8 }],
    [{ type: 'normal', count: 10 }, { type: 'fast', count: 10 }, { type: 'tank', count: 5 }, { type: 'boss', count: 1 }],
  ] as { type: string; count: number }[][],

  // Weapon stats
  weapons: {
    // Path weapons (traps)
    landmine: {
      name: 'Landmine',
      cost: 25,
      damage: 200,
      radius: 2.5, // explosion radius
      isPath: true,
      description: 'Explodiert bei Kontakt. Einmalig, hoher Schaden.',
      color: 0x555555,
    },
    spikeTrap: {
      name: 'Stachelfalle',
      cost: 15,
      damage: 8, // per tick
      radius: 1.0,
      slowFactor: 0.5,
      isPath: true,
      description: 'Dauerschaden + Verlangsamung. Bleibt bestehen.',
      color: 0x888888,
    },

    // Tower weapons
    arrowTower: {
      name: 'Pfeil-Turm',
      cost: 50,
      damage: 15,
      range: 6,
      fireRate: 2.0, // attacks per second
      isPath: false,
      description: 'Schnell, Einzelziel. Guter Allrounder.',
      color: 0x8B4513,
      projectileColor: 0xddaa44,
      projectileSpeed: 20,
    },
    cannonTower: {
      name: 'Kanonen-Turm',
      cost: 80,
      damage: 40,
      range: 5,
      fireRate: 0.7,
      splashRadius: 2.0,
      isPath: false,
      description: 'Langsam, aber Flächenschaden.',
      color: 0x444444,
      projectileColor: 0x333333,
      projectileSpeed: 12,
    },
    iceTower: {
      name: 'Eis-Turm',
      cost: 60,
      damage: 5,
      range: 5,
      fireRate: 1.5,
      slowFactor: 0.4,
      slowDuration: 2.0,
      isPath: false,
      description: 'Verlangsamt Gegner stark.',
      color: 0x88ccff,
      projectileColor: 0xaaddff,
      projectileSpeed: 15,
    },
    fireTower: {
      name: 'Feuer-Turm',
      cost: 70,
      damage: 8,
      range: 4,
      fireRate: 3.0,
      dotDamage: 5,
      dotDuration: 3.0,
      isPath: false,
      description: 'Flammen + Schaden über Zeit.',
      color: 0xff4400,
      projectileColor: 0xff6600,
      projectileSpeed: 18,
    },
    sniperTower: {
      name: 'Sniper-Turm',
      cost: 100,
      damage: 120,
      range: 12,
      fireRate: 0.4,
      isPath: false,
      description: 'Extreme Reichweite, hoher Einzelschaden.',
      color: 0x2c3e50,
      projectileColor: 0xffff00,
      projectileSpeed: 40,
    },
    teslaTower: {
      name: 'Tesla-Turm',
      cost: 120,
      damage: 25,
      range: 5,
      fireRate: 1.0,
      chainTargets: 3,
      isPath: false,
      description: 'Kettenblitz trifft bis zu 3 Gegner.',
      color: 0x9b59b6,
      projectileColor: 0xcc88ff,
      projectileSpeed: 30,
    },
    mortarTower: {
      name: 'Mörser-Turm',
      cost: 110,
      damage: 60,
      range: 10,
      fireRate: 0.5,
      splashRadius: 3.0,
      isPath: false,
      description: 'Extreme Reichweite, großer Flächenschaden.',
      color: 0x7f6b52,
      projectileColor: 0x664422,
      projectileSpeed: 8,
    },
    poisonTower: {
      name: 'Gift-Turm',
      cost: 90,
      damage: 3,
      range: 5,
      fireRate: 1.0,
      dotDamage: 10,
      dotDuration: 4.0,
      splashRadius: 2.5,
      isPath: false,
      description: 'Giftwolke: Flächenschaden über Zeit.',
      color: 0x27ae60,
      projectileColor: 0x44ff44,
      projectileSpeed: 10,
    },

    // ─── New Towers ─────────────────────────────
    laserTower: {
      name: 'Laser-Turm',
      cost: 130,
      damage: 12,
      range: 7,
      fireRate: 10.0, // ticks per second (continuous)
      isPath: false,
      description: 'Kontinuierlicher Strahl. Schaden steigt über Zeit.',
      color: 0xff2222,
      projectileColor: 0xff0000,
      projectileSpeed: 999,
    },
    windTower: {
      name: 'Wind-Turm',
      cost: 75,
      damage: 5,
      range: 5,
      fireRate: 0.8,
      isPath: false,
      description: 'Stößt Gegner auf dem Pfad zurück.',
      color: 0x88ddcc,
      projectileColor: 0xccffee,
      projectileSpeed: 25,
    },
    mageTower: {
      name: 'Magier-Turm',
      cost: 95,
      damage: 30,
      range: 8,
      fireRate: 1.2,
      isPath: false,
      description: 'Homing-Projektile durchbohren 2 Gegner.',
      color: 0x6644cc,
      projectileColor: 0xaa66ff,
      projectileSpeed: 12,
    },
    flamethrowerTower: {
      name: 'Flammenwerfer',
      cost: 85,
      damage: 6,
      range: 3.5,
      fireRate: 8.0,
      dotDamage: 3,
      dotDuration: 2.0,
      isPath: false,
      description: 'Kurze Reichweite, massiver Feuerschaden.',
      color: 0xff6600,
      projectileColor: 0xff4400,
      projectileSpeed: 15,
    },
    barrierTower: {
      name: 'Barriere-Turm',
      cost: 110,
      damage: 0,
      range: 4,
      fireRate: 0.5,
      slowFactor: 0.2,
      slowDuration: 3.0,
      isPath: false,
      description: 'Erzeugt Verlangsamungsfeld auf dem Pfad.',
      color: 0x4488ff,
      projectileColor: 0x4488ff,
      projectileSpeed: 0,
    },
    necromancerTower: {
      name: 'Nekromant-Turm',
      cost: 140,
      damage: 20,
      range: 6,
      fireRate: 0.6,
      isPath: false,
      description: 'Beschwört Skelette die Gegner angreifen.',
      color: 0x553388,
      projectileColor: 0x886ecc,
      projectileSpeed: 8,
    },
    earthquakeTower: {
      name: 'Erdbeben-Turm',
      cost: 125,
      damage: 35,
      range: 5,
      fireRate: 0.25,
      splashRadius: 4.0,
      isPath: false,
      description: 'Periodischer Flächenschaden + Stun.',
      color: 0x886644,
      projectileColor: 0xaa8844,
      projectileSpeed: 0,
    },
    healTower: {
      name: 'Heilturm',
      cost: 100,
      damage: 0,
      range: 0,
      fireRate: 1.0,
      isPath: false,
      description: 'Heilt +5 Basis-HP pro Sekunde.',
      color: 0x44ff88,
      projectileColor: 0x44ff88,
      projectileSpeed: 0,
    },

    // ─── New Traps ──────────────────────────────
    frostMine: {
      name: 'Frostmine',
      cost: 30,
      damage: 20,
      radius: 3.0,
      isPath: true,
      description: 'Einmalig: Friert alle Gegner 3s ein.',
      color: 0x88ccff,
    },
    goldMine: {
      name: 'Goldmine',
      cost: 40,
      damage: 0,
      radius: 0,
      isPath: true,
      description: 'Generiert +2 Gold pro Sekunde.',
      color: 0xffcc00,
    },
  },
} as const;

export type WeaponKey = keyof typeof BALANCE.weapons;
export type ZombieType = keyof typeof BALANCE.zombies;

export const WEAPON_KEYS: WeaponKey[] = Object.keys(BALANCE.weapons) as WeaponKey[];
